version: "3.7"

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
    - 6444:5432

  app:
    build: .
    volumes:
      - ./project:/project:rw
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - default
      - common-net
    ports:
    - 9080:8000

networks:
  default:
    driver: bridge
  common-net:
    external: true